# Generated by Django 5.2.6 on 2025-09-16 08:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('shoes', 'Shoes'), ('ball', 'Ball'), ('shin guards', 'Shin Guards'), ('jersey', 'Jersey'), ('shorts', 'Shorts'), ('socks', 'Socks'), ('goalkeeper gloves', 'Goalkeeper Gloves')], default='shoes', max_length=30)),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
    ]
