# Generated by Django 5.2.6 on 2025-11-19 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_user'),
    ]

    operations = [
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS main_product CASCADE;",
            reverse_sql="",
        )
    ]
