# Generated by Django 5.2.6 on 2025-11-19 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20251119_1601'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                DROP TABLE IF EXISTS main_product CASCADE;
                DELETE FROM django_migrations WHERE app='main';
            """,
            reverse_sql="",
        )
    ]
